// Code generated by protoc-gen-go. DO NOT EDIT.
// source: plugin.proto

/*
Package docker_protobuf_plugin is a generated protocol buffer package.

It is generated from these files:
	plugin.proto

It has these top-level messages:
	WatchSelectors
	StoreObject
	TLSAuthorization
*/
package docker_protobuf_plugin

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/protoc-gen-go/descriptor"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type WatchSelectors struct {
	// supported by all object types
	Id               *bool  `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	IdPrefix         *bool  `protobuf:"varint,2,opt,name=id_prefix,json=idPrefix" json:"id_prefix,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *WatchSelectors) Reset()                    { *m = WatchSelectors{} }
func (m *WatchSelectors) String() string            { return proto.CompactTextString(m) }
func (*WatchSelectors) ProtoMessage()               {}
func (*WatchSelectors) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *WatchSelectors) GetId() bool {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return false
}

func (m *WatchSelectors) GetIdPrefix() bool {
	if m != nil && m.IdPrefix != nil {
		return *m.IdPrefix
	}
	return false
}

type StoreObject struct {
	WatchSelectors   *WatchSelectors `protobuf:"bytes,1,req,name=watch_selectors,json=watchSelectors" json:"watch_selectors,omitempty"`
	XXX_unrecognized []byte          `json:"-"`
}

func (m *StoreObject) Reset()                    { *m = StoreObject{} }
func (m *StoreObject) String() string            { return proto.CompactTextString(m) }
func (*StoreObject) ProtoMessage()               {}
func (*StoreObject) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *StoreObject) GetWatchSelectors() *WatchSelectors {
	if m != nil {
		return m.WatchSelectors
	}
	return nil
}

type TLSAuthorization struct {
	// Roles contains the acceptable TLS OU roles for the handler.
	Roles []string `protobuf:"bytes,1,rep,name=roles" json:"roles,omitempty"`
	// Insecure is set to true if this method does not require
	// authorization. NOTE: Specifying both "insecure" and a nonempty
	// list of roles is invalid. This would fail at codegen time.
	Insecure         *bool  `protobuf:"varint,2,opt,name=insecure" json:"insecure,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *TLSAuthorization) Reset()                    { *m = TLSAuthorization{} }
func (m *TLSAuthorization) String() string            { return proto.CompactTextString(m) }
func (*TLSAuthorization) ProtoMessage()               {}
func (*TLSAuthorization) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *TLSAuthorization) GetRoles() []string {
	if m != nil {
		return m.Roles
	}
	return nil
}

func (m *TLSAuthorization) GetInsecure() bool {
	if m != nil && m.Insecure != nil {
		return *m.Insecure
	}
	return false
}

var E_Deepcopy = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.MessageOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         70000,
	Name:          "docker.protobuf.plugin.deepcopy",
	Tag:           "varint,70000,opt,name=deepcopy,def=1",
	Filename:      "plugin.proto",
}

var E_StoreObject = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.MessageOptions)(nil),
	ExtensionType: (*StoreObject)(nil),
	Field:         70001,
	Name:          "docker.protobuf.plugin.store_object",
	Tag:           "bytes,70001,opt,name=store_object,json=storeObject",
	Filename:      "plugin.proto",
}

var E_TlsAuthorization = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.MethodOptions)(nil),
	ExtensionType: (*TLSAuthorization)(nil),
	Field:         73626345,
	Name:          "docker.protobuf.plugin.tls_authorization",
	Tag:           "bytes,73626345,opt,name=tls_authorization,json=tlsAuthorization",
	Filename:      "plugin.proto",
}

func init() {
	proto.RegisterType((*WatchSelectors)(nil), "docker.protobuf.plugin.WatchSelectors")
	proto.RegisterType((*StoreObject)(nil), "docker.protobuf.plugin.StoreObject")
	proto.RegisterType((*TLSAuthorization)(nil), "docker.protobuf.plugin.TLSAuthorization")
	proto.RegisterExtension(E_Deepcopy)
	proto.RegisterExtension(E_StoreObject)
	proto.RegisterExtension(E_TlsAuthorization)
}

func init() { proto.RegisterFile("plugin.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 338 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x90, 0xcf, 0x4a, 0xeb, 0x40,
	0x14, 0xc6, 0x69, 0x6e, 0x2f, 0xa4, 0x93, 0xd2, 0xdb, 0x3b, 0x88, 0x84, 0x0a, 0x5a, 0x5a, 0x90,
	0xac, 0x52, 0xe8, 0x32, 0xe0, 0x42, 0x74, 0xa9, 0x54, 0x52, 0xc1, 0x9d, 0x21, 0x9d, 0x39, 0x4d,
	0x47, 0x43, 0xcf, 0x30, 0x33, 0xa1, 0xd5, 0x77, 0xf0, 0x25, 0x7c, 0x37, 0x17, 0xee, 0xf4, 0x0d,
	0x24, 0x49, 0xff, 0x18, 0x69, 0x71, 0xf9, 0x9d, 0x99, 0xf3, 0xfb, 0xce, 0xf7, 0x91, 0xa6, 0x4c,
	0xb3, 0x44, 0xcc, 0x7d, 0xa9, 0xd0, 0x20, 0x3d, 0xe4, 0xc8, 0x1e, 0x41, 0x95, 0x6a, 0x92, 0x4d,
	0xfd, 0xf2, 0xb5, 0xd3, 0x4d, 0x10, 0x93, 0x14, 0x06, 0xeb, 0xf9, 0x80, 0x83, 0x66, 0x4a, 0x48,
	0x83, 0xab, 0xbf, 0xbd, 0x33, 0xd2, 0xba, 0x8b, 0x0d, 0x9b, 0x8d, 0x21, 0x05, 0x66, 0x50, 0x69,
	0xda, 0x22, 0x96, 0xe0, 0x6e, 0xad, 0x5b, 0xf3, 0xec, 0xd0, 0x12, 0x9c, 0x1e, 0x91, 0x86, 0xe0,
	0x91, 0x54, 0x30, 0x15, 0x4b, 0xd7, 0x2a, 0xc6, 0xb6, 0xe0, 0x37, 0x85, 0xee, 0xdd, 0x13, 0x67,
	0x6c, 0x50, 0xc1, 0x68, 0xf2, 0x00, 0xcc, 0xd0, 0x11, 0xf9, 0xb7, 0xc8, 0x69, 0x91, 0x5e, 0xe3,
	0xdc, 0x5a, 0xd7, 0xf2, 0x9c, 0xe1, 0xa9, 0xbf, 0xfb, 0x42, 0xbf, 0x6a, 0x1e, 0xb6, 0x16, 0x15,
	0xdd, 0xbb, 0x24, 0xed, 0xdb, 0xab, 0xf1, 0x79, 0x66, 0x66, 0xa8, 0xc4, 0x73, 0x6c, 0x04, 0xce,
	0xe9, 0x01, 0xf9, 0xab, 0x30, 0x85, 0x1c, 0xfd, 0xc7, 0x6b, 0x84, 0xa5, 0xa0, 0x1d, 0x62, 0x8b,
	0xb9, 0x06, 0x96, 0x29, 0xd8, 0x5c, 0xb9, 0xd2, 0xc1, 0x05, 0xb1, 0x39, 0x80, 0x64, 0x28, 0x9f,
	0xe8, 0x89, 0x5f, 0x76, 0xb2, 0xbd, 0xe4, 0x1a, 0xb4, 0x8e, 0x13, 0x18, 0xc9, 0x9c, 0xae, 0xdd,
	0x8f, 0xd7, 0x7a, 0xbe, 0x1e, 0xd4, 0x8d, 0xca, 0x20, 0xdc, 0x2c, 0x06, 0x82, 0x34, 0x75, 0x1e,
	0x35, 0xc2, 0x32, 0xeb, 0xaf, 0xa0, 0xcf, 0x02, 0xe4, 0x0c, 0xfb, 0xfb, 0xb2, 0x7f, 0x6b, 0x2e,
	0x74, 0xf4, 0x56, 0x04, 0x4b, 0xf2, 0xdf, 0xa4, 0x3a, 0x8a, 0x2b, 0xb1, 0x8f, 0x77, 0xf8, 0x99,
	0x19, 0xf2, 0xb5, 0xdd, 0xfb, 0xdb, 0x4b, 0xbf, 0xf0, 0xf3, 0xf6, 0xf9, 0xfd, 0x6c, 0x32, 0x6c,
	0x9b, 0x54, 0x57, 0x26, 0x5f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x6c, 0x8f, 0xbd, 0xe0, 0x57, 0x02,
	0x00, 0x00,
}
