/*
 * Swagger Test
 *
 * description.
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type Book struct {

	Name string `json:"name"`

	Author string `json:"author,omitempty"`

	Press string `json:"press,omitempty"`

	// book status in the store
	State string `json:"state,omitempty"`
}
